config/routes.rb
Rails.application.routes.draw do
  resources :flats

  devise_for :users

  root to: "pages#home"

  get "dashboard", to: "pages#dashboard"
  get "services", to: "pages#services"
  get "about", to: "pages#about"



  resources :vehicules

  resources :commentaires, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :pieces

  resources :members, only: [:index, :new, :create, :edit, :update, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_blacknavbar.html.erb
<div class="blacknav-container">

  <div class="blacknav-gauche">
    <a href="/"><%= image_tag("logoRondTrans.png", alt: "Supprimer", size: "60x60") %></a>
  </div>

  <div class="nvrainav-container">
    <%= link_to "Accueil", root_path, class: ("active" if current_page?(root_path)) %>
    <%= link_to "Nos Véhicules", vehicules_path, class: ("active" if current_page?(vehicules_path)) %>
    <%= link_to "Nos pièces", pieces_path, class: ("active" if current_page?(pieces_path)) %>
    <%= link_to "Commentaires", commentaires_path, class: ("active" if current_page?(commentaires_path)) %>
    <%= link_to "Notre équipe", members_path, class: ("active" if current_page?(members_path)) %>
    <%= link_to "Contact", about_path, class: ("active" if current_page?(about_path)) %>
    <%= link_to "Services", services_path, class: ("active" if current_page?(services_path)) %>
    <% if user_signed_in? %>
      <%= link_to dashboard_path, class: ("active" if current_page?(dashboard_path)) do %>
        <i class="fa-solid fa-fingerprint" style="color: #ffffff;"></i>
      <% end %>
    <% end %>
  </div>



  <div class="blacknav-droite">
    <p>Contact:</p>
    <h4>03 21 89 56 00</h4>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-container">

  <div class="footer-haut">

    <div class="footer-adresse">

      <div class="footer-local">
        <div class="footer-adrss-longue">
          <p><i class="fa-solid fa-location-dot" style="color: #ffffff;"></i></p>
          <div>
            <p>801 Av. Maxence Van Der Meersch,</p>
            <p>62780 Cucq</p>
          </div>

        </div>
        <p><i class="fa-solid fa-phone" style="color: #ffffff;"></i><a href="tel:03-21-89-56-00">03 21 89 56 00</a></p>
        <p><i class="fa-solid fa-envelope" style="color: #ffffff;"></i><a href="mailto:contact@planete-alfa.fr" class="emailf">contact@planete-alfa.fr</a></p>
      </div>

      <div class="footer-social">
        <a href="https://www.facebook.com/Planetealfa/?locale=fr_FR" target="_blank" class="footer-fb"><i class="fa-brands fa-facebook" style="color: #ffffff;"></i> Facebook</a>
      </div>

    </div>

    <div class="footer-calendrier">

      <div class="footer-jour">
        <p><i class="fas fa-calendar-alt" style="color: #ffffff;"></i> Lun</p>
        <p>14:00 - 18:00</p>
      </div>

      <div class="footer-jour">
        <p><i class="fas fa-calendar-alt" style="color: #ffffff;"></i> Mar</p>
        <p>08:30 - 12:00, 14:00 - 18:00</p>
      </div>

      <div class="footer-jour">
        <p><i class="fas fa-calendar-alt" style="color: #ffffff;"></i> Mer</p>
        <p>08:30 - 12:00, 14:00 - 18:00</p>
      </div>

      <div class="footer-jour">
        <p><i class="fas fa-calendar-alt" style="color: #ffffff;"></i> Jeu</p>
        <p>08:30 - 12:00, 14:00 - 18:00</p>
      </div>

      <div class="footer-jour">
        <p><i class="fas fa-calendar-alt" style="color: #ffffff;"></i> Ven</p>
        <p>08:30 - 12:00, 14:00 - 18:00</p>
      </div>

      <div class="footer-jour">
        <p><i class="fas fa-calendar-alt" style="color: #ffffff;"></i> Sam</p>
        <p>08:30 - 12:00, 14:00 - 17:00</p>
      </div>

      <div class="footer-jour">
        <p><i class="fas fa-calendar-alt" style="color: #ffffff;"></i> Dim</p>
        <p>Fermé</p>
      </div>

    </div>

  </div>



</div>

app/views/shared/_footerbas.html.erb
<div class="footer-bas">
  <p>© Planète Alfa Copyright 2025 - By FLTdev</p>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_petitenavbar.html.erb
<div class="navking" data-controller="navigation">
  <div class="petit-nav-king">
    <div class="petit-blacknav-container">

      <div class="blacknav-gauche">
        <a href="/"><%= image_tag("logoRondTrans.png", alt: "Supprimer", size: "60x60") %></a>
      </div>


      <div class="navbar-fav-container" data-action="click->navigation#openNav" data-navigation-target="lignes">
        <div class="nav-button-nav">
          <i class="fa-solid fa-bars" style="color: #ffffff;"></i>
        </div>
      </div>

      <div class="navbar-fav-container d-none" data-action="click->navigation#closeNav" data-navigation-target="croix">
        <div class="nav-button-nav">
          <i class="fa-solid fa-xmark" style="color: #ffffff;"></i>
        </div>
      </div>



      <div class="blacknav-droite">
        <p>Contact:</p>
        <h4>03 21 89 56 00</h4>
      </div>

    </div>
  </div>


  <div class="navbar-petit-format d-none" data-navigation-target="popnav">
    <div class="navbar-petit-format-link">
      <%= link_to "Accueil", root_path, class: ("active" if current_page?(root_path)) %>
      <%= link_to "Nos Véhicules", vehicules_path, class: ("active" if current_page?(vehicules_path)) %>
      <%= link_to "Nos pièces", pieces_path, class: ("active" if current_page?(pieces_path)) %>
      <%= link_to "Commentaires", commentaires_path, class: ("active" if current_page?(commentaires_path)) %>
      <%= link_to "Notre équipe", members_path, class: ("active" if current_page?(members_path)) %>
      <%= link_to "Contact", about_path, class: ("active" if current_page?(about_path)) %>
      <%= link_to "Services", services_path, class: ("active" if current_page?(services_path)) %>
      <% if user_signed_in? %>
        <%= link_to "Dashboard", dashboard_path, class: ("active" if current_page?(dashboard_path)) %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_vrainavbar.html.erb
<div class="vrainav-container">
  <%= link_to "Accueil", root_path, class: ("active" if current_page?(root_path)) %>
  <%= link_to "Nos occasions", vehicules_path, class: ("active" if current_page?(vehicules_path)) %>
  <%= link_to "Nos pièces", pieces_path, class: ("active" if current_page?(pieces_path)) %>
  <%= link_to "Commentaires", commentaires_path, class: ("active" if current_page?(commentaires_path)) %>
  <%= link_to "Notre équipe", members_path, class: ("active" if current_page?(members_path)) %>
  <%= link_to "Dashboard", dashboard_path, class: ("active" if current_page?(dashboard_path)) %>
</div>