config/routes.rb
Rails.application.routes.draw do
  resources :flats

  devise_for :users

  root to: "pages#home"

  get "dashboard", to: "pages#dashboard"
  get "services", to: "pages#services"
  get "about", to: "pages#about"



  resources :vehicules

  resources :commentaires, only: [:index, :new, :create, :edit, :update, :destroy]

  resources :pieces

  resources :members, only: [:index, :new, :create, :edit, :update, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/pages/about.html.erb
<div class="about-container">

  <div class="about-titre">
    <h1>Contact</h1>
  </div>

  <div class="about-info-content">

    <div class="about-address-container">
      <div class="about-address">

        <div class="about-local">
          <div class="about-adrss-longue">
            <p><i class="fa-solid fa-location-dot" style="color: #ffffff;"></i></p>
            <div>
              <p>801 Av. Maxence Van Der Meersch, 62780 Cucq</p>

            </div>

          </div>
          <p><i class="fa-solid fa-phone" style="color: #ffffff;"></i><a href="tel:03-21-89-56-00">03 21 89 56 00</a></p>
          <p><i class="fa-solid fa-envelope" style="color: #ffffff;"></i><a href="mailto:contact@planete-alfa.fr">contact@planete-alfa.fr</a></p>
        </div>


        <div class="about-calendrier">

          <div class="about-jour">
            <p><i class="fas fa-calendar-alt" style="color: #ffffff;"></i> Lun</p>
            <p>14:00 - 18:00</p>
          </div>

          <div class="about-jour">
            <p><i class="fas fa-calendar-alt" style="color: #ffffff;"></i> Mar</p>
            <p>08:30 - 12:00, 14:00 - 18:00</p>
          </div>

          <div class="about-jour">
            <p><i class="fas fa-calendar-alt" style="color: #ffffff;"></i> Mer</p>
            <p>08:30 - 12:00, 14:00 - 18:00</p>
          </div>

          <div class="about-jour">
            <p><i class="fas fa-calendar-alt" style="color: #ffffff;"></i> Jeu</p>
            <p>08:30 - 12:00, 14:00 - 18:00</p>
          </div>

          <div class="about-jour">
            <p><i class="fas fa-calendar-alt" style="color: #ffffff;"></i> Ven</p>
            <p>08:30 - 12:00, 14:00 - 18:00</p>
          </div>

          <div class="about-jour">
            <p><i class="fas fa-calendar-alt" style="color: #ffffff;"></i> Sam</p>
            <p>08:30 - 12:00, 14:00 - 17:00</p>
          </div>

          <div class="about-jour">
            <p><i class="fas fa-calendar-alt" style="color: #ffffff;"></i> Dim</p>
            <p>Fermé</p>
          </div>

        </div>

      </div>
    </div>


      <div class="map-container">
        <div class="about-map">
          <div style="width: 100%; height: 450px;"
            data-controller="map"
            data-map-markers-value="<%= @markers.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
      </div>


  </div>


</div>

app/views/pages/dashboard.html.erb
<div class="dash-content" data-controller="dashboard">
  <div class="dash-title">

    <div class="dash-titre-haut">
      <h1>Tableau de bord</h1>
    </div>

  </div>

    <!-- icon choix  -->

  <div class="dash-icon-container">

    <div class="dash-icon-circle" data-action="click->dashboard#openvehicule">
      <i class="fa-solid fa-car"></i>
    </div>

    <div class="dash-icon-circle" data-action="click->dashboard#openpiece">
      <i class="fa-solid fa-gear"></i>
    </div>
    <div class="dash-icon-circle" data-action="click->dashboard#opencom">
      <i class="fa-solid fa-comment"></i>
    </div>
    <div class="dash-icon-circle" data-action="click->dashboard#openmember">
      <i class="fa-solid fa-clipboard-user"></i>
    </div>

  </div>


    <!-- vehicules -->
  <div data-dashboard-target="sectionvehicule">


    <div class="dash-title">

      <div class="dash-titre-categ">
        <h3>Véhicules</h3>
      </div>
      <div class="dash-titre-bas">
        <%= link_to "Ajouter +", new_vehicule_path, class: "dash-add-btn" %>
        <h6> <%= Vehicule.count %> articles en vente</h6>
      </div>


    </div>



    <div class="dash-all-vehicule-content">
      <div class="dash-all-vehicules">

        <% @vehicules.each do |vehicule| %>
            <div class="testdash dashborder deco-none">
              <%= link_to vehicule_path(vehicule), data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer ?" }, class: "deco-none dash-corbeille" do %>
                <i class="fa-solid fa-trash" style="color: #ffffff;"></i>
              <% end %>
              <%= link_to edit_vehicule_path(vehicule), class: "deco-none dash-modif" do %>
                <i class="fa-solid fa-pen-to-square" style="color: #ffffff;"></i>
              <% end %>
              <% if vehicule.photo.present? %>
                <%= cl_image_tag vehicule.photo.key, height: 40, width: 60, crop: :fill, class: "dash-img" %>
              <% else %>
                <p>Sans Image </p>
              <% end %>
              <%= link_to "#{vehicule.marque} #{vehicule.modele}", vehicule_path(vehicule), class: "deco-none dash-nom" %>
            </div>


        <% end %>

      </div>
    </div>

  </div>



  <!-- pieces -->
  <div data-dashboard-target="sectionpiece">

    <div class="dash-title">
      <div class="dash-titre-categ">
        <h3>Pièces</h3>
      </div>
      <div class="dash-titre-bas">
        <%= link_to "Ajouter +", new_piece_path, class: "dash-add-btn" %>
        <h6> <%= Piece.count %> pieces en vente</h6>
      </div>

    </div>


    <div class="dash-all-vehicule-content">
      <div class="dash-all-vehicules">

        <% @pieces.each do |piece| %>
            <div class="testdash dashborder deco-none">
              <%= link_to piece_path(piece), data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer ?" }, class: "deco-none dash-corbeille" do %>
                <i class="fa-solid fa-trash" style="color: #ffffff;"></i>
              <% end %>
              <%= link_to edit_piece_path(piece), class: "deco-none dash-modif" do %>
                <i class="fa-solid fa-pen-to-square" style="color: #ffffff;"></i>
              <% end %>
              <%= cl_image_tag piece.photo.key, height: 40, width: 60, crop: :fill, class: "dash-img" %>
              <div class="dash-piece-nom">
                <%= link_to "#{piece.nom}", piece_path(piece), class: "deco-none dash-nom" %>
              </div>
              <div class="dash-piece-desc">
                <%= piece.description.slice(0, 50) %>
              </div>
              <div class="dash-piece-prix">
                <%= piece.prix %>€
              </div>
            </div>


        <% end %>

      </div>
    </div>

  </div>



  <!-- commentaires -->

  <div data-dashboard-target="sectioncom">


    <div class="dash-title">
      <div class="dash-titre-categ">
        <h3>Commentaires</h3>
      </div>
      <div class="dash-titre-bas">
        <p> </p>
        <h6> <%= Commentaire.count %> commentaires sur le site</h6>
      </div>

    </div>

    <div class="dash-all-vehicule-content">
      <div class="dash-all-com">

        <div class="dash-commentaire-content">

          <% @commentaires.each do |commentaire| %>
            <div class="one-com <%= commentaire.id.even? ? 'com-bg-strggrey' : 'com-bg-grey' %>">
              <div class="dash-com-client-address">
                <p><strong><%= commentaire.nom %> <%= commentaire.prenom %></strong></p>
                <p><%= commentaire.email %> </p>
              </div>

              <p>Text: <%= commentaire.text.slice(0, 90) %><% if commentaire.text.length > 90 %>...<% end %></p>

              <% if commentaire.reponse.present? %>
                <p class="dash-yes-rep">Reponse: <%= commentaire.reponse.slice(0, 85) %><% if commentaire.reponse.length > 85 %>...<% end %></p>
              <% else %>
                <p class="dash-no-rep">Aucune reponse</p>
              <% end %>

              <div class="dash-com-date">
                <p>Date: <%= commentaire.created_at.strftime("%d/%m/%Y") %> </p>
              </div>

              <div class="dash-com-fav">
                <div>
                  <%= link_to edit_commentaire_path(commentaire), class: "deco-none dash-modif" do %>
                    <i class="fa-solid fa-pen-to-square" style="color: #ffffff;"></i>
                  <% end %>
                </div>
                <div>
                  <%= link_to commentaire_path(commentaire), data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer ?" }, class: "deco-none dash-corbeille" do %>
                    <i class="fa-solid fa-trash" style="color: #ffffff;"></i>
                  <% end %>
                </div>
              </div>

            </div>


          <% end %>

        </div>
      </div>
    </div>

  </div>


    <!-- members -->

  <div data-dashboard-target="sectionmember">

    <div class="dash-title">

      <div class="dash-titre-categ">
        <h3>Team</h3>
      </div>
      <div class="dash-titre-bas">
        <%= link_to "Ajouter +", new_member_path, class: "dash-add-btn" %>
        <h6> <%= Member.count %> personnes</h6>
      </div>

    </div>




    <div class="dash-all-vehicule-content">
      <div class="dash-all-vehicules">

        <% @members.each do |member| %>
            <div class="testdash dashborder deco-none">
              <%= link_to member_path(member), data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer ?" }, class: "deco-none dash-corbeille" do %>
                <i class="fa-solid fa-trash" style="color: #ffffff;"></i>
              <% end %>
              <%= link_to edit_member_path(member), class: "deco-none dash-modif" do %>
                <i class="fa-solid fa-pen-to-square" style="color: #ffffff;"></i>
              <% end %>
              <%= cl_image_tag member.photo.key, height: 40, width: 60, crop: :fill, class: "dash-img" %>
              <div class="dash-member-name">
                <%= member.nom %> <%= member.prenom %>
              </div>
            </div>


        <% end %>

      </div>
    </div>

  </div>

</div>

app/views/pages/home.html.erb
<div class="hero-video">
  <%= video_tag "mainvideomute.mp4", type: "video/mp4", autoplay: true, loop: true, muted: true, id: "home-videoo", preload: "auto", playsinline: true %>




  <div class="text-sur-video">
    <h1>
      <div class="text-sur-video-div-a-flex">
        <div class="text-sur-video-planete">Planète</div>
        <div><span>a</span>lfa</div>
      </div>
    </h1>
  </div>

  <div class="ball-big-contener">
    <div class="ball-contener">
      <div class="ball">
        <a href="#who" class="cheveron-down">
          <i class="fa-solid fa-chevron-down" style="color: #ffffff;"></i>
        </a>
      </div>
    </div>
  </div>

  <div class="home-gray-bar">
  </div>
</div>






<!-- Qui sommes nous ? (who) + carrou pour bgc -->
<div class="home-bgc-grisf">


  <!-- ---------------------------- -->
  <!-- ---------------------------- -->
  <!-- QUI SOMMES NOUS ?? (WHO) -->
  <!-- ---------------------------- -->
  <!-- ---------------------------- -->

  <div class="who-container" id="who">

    <div class="who-titre">

      <div class="scroll-container">
        <div class="scroll-text">
          <h2>Planète Alfa</h2>
        </div>
      </div>

    </div>


    <div class="who-gauche-droite">

      <div class="who-gauche">
        <%= image_tag "who2.jpg", height: 400, width: 560, crop: :fill, class:"who-gauche-img" %>
      </div>

      <div class="who-droite">
        <div class="who-droite-text">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sit, quam. Fugit, impedit mollitia totam sapiente voluptatem atque ipsam quia ipsum et fugiat nihil assumenda in consectetur dolorem. Itaque, non nemo.<br></p>
          <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Iure ipsa aliquam suscipit ex laboriosam officiis quisquam harum amet autem dolores accusamus nihil iste eaque quo tenetur quaerat, eveniet nobis dolore?</p>
          <div class="div-btn-pa">
            <%= link_to "Prendre contact", about_path, class:"btn-pa" %>
          </div>
        </div>
      </div>

    </div>

  </div>

  <!-- SCRIPT QUI SOMMES NOUS ?? (title / img / txt) -->

  <script>
    window.addEventListener('scroll', function() {
      var scrollPosition = window.scrollY;
      var scrollTitre = document.querySelector('.scroll-text');

      if (scrollPosition > 120) {
        scrollTitre.classList.add('show');
      } else {
        scrollTitre.classList.remove('show');
      }
    });

    if (window.innerWidth > 640) {
      window.addEventListener('scroll', function() {
        var scrollPosition = window.scrollY;
        var scrollImg = document.querySelector('.who-gauche img');

        if (scrollPosition > 390) {
          scrollImg.classList.add('show');
        } else {
          scrollImg.classList.remove('show');
        }
      });
    }



    window.addEventListener('scroll', function() {
      var scrollPosition = window.scrollY;
      var scrollText = document.querySelector('.who-droite-text');

      if (scrollPosition > 600) {
        scrollText.classList.add('show');
      } else {
        scrollText.classList.remove('show');
      }
    });


  </script>


  <!-- ---------------------------- -->
  <!-- ---------------------------- -->
  <!-- NOS VEHICULES  -->
  <!-- ---------------------------- -->
  <!-- ---------------------------- -->


  <div class="home-vehicules-container" id="#">

    <div class="home-vehicules-titre">

      <div class="scroll-container">
        <div class="text-home-vehicule">
          <h2>Nos Vehicules</h2>
        </div>
      </div>

    </div>


    <div class="home-vehicules-gauche-droite">

      <div class="home-vehicules-gauche">
        <div class="home-vehicules-gauche-text">
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima quia fugit expedita perspiciatis adipisci, explicabo quos nemo corrupti facere atque nulla quis repellat quas inventore aspernatur deserunt dolore. Doloremque, maxime!<br></p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore nulla quibusdam neque, tempora tenetur error, ducimus culpa, esse cumque cupiditate itaque reiciendis ratione adipisci dolorem libero perferendis ipsum? Porro, aliquam.</p>
          <div class="div-btn-pa">
            <%= link_to "Nos Vehicules", vehicules_path, class:"btn-pa" %>
          </div>
        </div>
      </div>

      <div class="home-vehicules-droite">
        <%= image_tag "home_nv.png", height: 400, width: 560, crop: :fill, class:"home-vehicules-droite-img" %>
      </div>

    </div>

  </div>

  <!-- SCRIPT NOS VEHICULES (title img  txt) -->

  <script>
    window.addEventListener('scroll', function() {
      var scrollPosition = window.scrollY;
      var scrollTitre = document.querySelector('.text-home-vehicule');

      if (scrollPosition > 1015) {
        scrollTitre.classList.add('show');
      } else {
        scrollTitre.classList.remove('show');
      }
    });


    window.addEventListener('scroll', function() {
      var scrollPosition = window.scrollY;
      var scrollImg = document.querySelector('.home-vehicules-droite-img');

      if (scrollPosition > 1300) {
        scrollImg.classList.add('show');
      } else {
        scrollImg.classList.remove('show');
      }
    });




    window.addEventListener('scroll', function() {
      var scrollPosition = window.scrollY;
      var scrollText = document.querySelector('.home-vehicules-gauche-text');
      console.log(scrollPosition);

      if (scrollPosition > 1188) {
        scrollText.classList.add('show');
      } else {
        scrollText.classList.remove('show');
      }
    });


  </script>



  <!-- test carrou -->




  <div class="carrou-body">


    <div>
      <h2>Les derniers arrivages</h2>
    </div>

    <div class="container">
        <input type="radio" name="slider" id="item-1" checked>
        <input type="radio" name="slider" id="item-2">
        <input type="radio" name="slider" id="item-3">
      <div class="cards">
        <label class="card" for="item-1" id="song-1">
          <%= cl_image_tag @vehicule1.photo.key %>
        </label>
        <label class="card" for="item-2" id="song-2">
          <%= cl_image_tag @vehicule2.photo.key %>
        </label>
        <label class="card" for="item-3" id="song-3">
          <%= cl_image_tag @vehicule3.photo.key %>
        </label>
      </div>
      <div class="player">
        <div class="upper-part">

          <div class="info-area" id="test">

            <label class="song-info" id="song-info-1">
              <div class="flex">
                <div class="title"><%= @vehicule1.marque %></div>
                <div class="title"><%= @vehicule1.modele %></div>
              </div>
              <div class="flex-bas">
                <div class="time"><%= number_with_precision(@vehicule1.kilometrage.to_i, precision: 0, delimiter: ' ', separator: '.') %> Km</div>
                <div class="carrou-link">
                  <div class="div-btn-pa">
                    <%= link_to "Voir +", vehicule_path(@vehicule1), class:"btn-pa" %>
                  </div>
                </div>
              </div>
            </label>

            <label class="song-info" id="song-info-2">
              <div class="flex">
                <div class="title"><%= @vehicule2.marque %></div>
                <div class="title"><%= @vehicule2.modele %></div>
              </div>
              <div class="flex-bas">
                <div class="time"><%= number_with_precision(@vehicule2.kilometrage, precision: 0, delimiter: ' ', separator: '.') %> Km</div>
                <div class="carrou-link">
                  <div class="div-btn-pa">
                    <%= link_to "Voir +", vehicule_path(@vehicule2), class:"btn-pa" %>
                  </div>
                </div>
              </div>
            </label>

            <label class="song-info" id="song-info-3">
              <div class="flex">
                <div class="title"><%= @vehicule3.marque %></div>
                <div class="title"><%= @vehicule3.modele %></div>
              </div>
              <div class="flex-bas">
                <div class="time"><%= number_with_delimiter(@vehicule3.kilometrage.to_i, delimiter: ' ', separator: '.', precision: 0) %> Km</div>


                <div class="carrou-link">
                  <div class="div-btn-pa">
                    <%= link_to "Voir +", vehicule_path(@vehicule3), class:"btn-pa" %>
                  </div>
                </div>
              </div>
            </label>

          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- script du carroussel entier -->
  <script>
    window.addEventListener('scroll', function() {
      var scrollPosition = window.scrollY;
      var scrollCarrou = document.querySelector('.carrou-body');

      if (scrollPosition > 1889) {
        scrollCarrou.classList.add('show');
      } else {
        scrollCarrou.classList.remove('show');
      }
    });
  </script>

  <div class="home-ns-container">
    <div class="home-ns-content">
      <div class="home-ns-title">Nos Services</div>

      <div class="home-ns-list-container">

        <div class="home-ns-carre-text">
          <div class="home-ns-carre"></div>
          <p>Reprogrammation</p>
        </div>

        <div class="home-ns-carre-text">
          <div class="home-ns-carre"></div>
          <p>Service carte grise</p>
        </div>

        <div class="home-ns-carre-text">
          <div class="home-ns-carre"></div>
          <p>Extension de garantie</p>
        </div>

        <div class="home-ns-carre-text">
          <div class="home-ns-carre"></div>
          <p>Clé de voiture</p>
        </div>

        <div class="home-ns-carre-text">
          <div class="home-ns-carre"></div>
          <p>Préparation pré-contrôle technique</p>
        </div>

        <div class="home-ns-carre-text">
          <div class="home-ns-carre"></div>
          <p>Financement avec Financo</p>
        </div>


      </div>

      <div class="home-ns-btn-container">
        <%= link_to "Nos services", services_path %>
      </div>

    </div>
  </div>




</div>

app/views/pages/services.html.erb
<div class="service-contener">
  <div class="service-titre">
    <h1>Nos Services</h1>
  </div>


  <div class="service-block">
    <div class="service-rond-titre service-titre-1">
      <div class="service-rond">
        <h2>1</h2>
      </div>
      <h2>Reprogrammation</h2>
    </div>
    <div class="service-text-1">
      <p>Nous offrons un service de reprogrammation qui comprend:</p>
      <br>
      <p>- La conversion bio éthanol.</p>
      <p>- L'optimisation de la puissance/couple.</p>
      <p>- La reprogrammation du calculateur.</p>
      <br>
      <p>Avec notre équipe de professionnels, vous pouvez être assuré d'obtenir les meilleures performances de votre véhicule.</p>
    </div>
  </div>



  <div class="service-block">
    <div class="service-rond-titre service-titre-2">
      <div class="service-rond">
        <h2>2</h2>
      </div>
      <h2>Service carte grise</h2>
      <%= image_tag "bbrtrans.png" %>
    </div>

    <div class="service-text-2">
      <p>Nous offrons également un service de carte grise qui comprend:</p>
      <br>
      <p>- le changement de titulaire</p>
      <p>- le changement d'état civil ou d'adresse.</p>
      <p>- la demande de duplicata en cas de perte/vol.</p>
      <p>- la demande de démarche de COC ou de véhicule de collection.</p>
      <p>- le changement de carburant et le jeu de plaque.</p>
      <p>- Nous pouvons vous aider à obtenir rapidement et facilement votre nouvelle carte grise.</p>
    </div>
  </div>




  <div class="service-block">
    <div class="service-rond-titre service-titre-3">
      <div class="service-rond">
        <h2>3</h2>
      </div>
      <h2>Extension de garantie</h2>
    </div>
    <div class="service-text-3">
      <p>Nous offrons la possibilité d'étendre votre garantie de voiture jusqu'à 48 mois.</p>
      <p>Vous pouvez être tranquille en sachant que votre véhicule est couvert contre les pannes et les dommages pendant une période prolongée.</p>
    </div>
  </div>



  <div class="service-block">
    <div class="service-rond-titre service-titre-4">
      <div class="service-rond">
        <h2>4</h2>
      </div>
      <h2>Clé de voiture</h2>
    </div>
    <div class="service-text-4">
      <p>Nous proposons également des services de clé de voiture tels que:</p>
      <br>
      <p>- La duplication de clé.</p>
      <p>- La résolution des problèmes de perte problèmes de (codage/décodage) pour toutes les marques et modèles de voitures.</p>
    </div>
  </div>



  <div class="service-block">
    <div class="service-rond-titre service-titre-5">
      <div class="service-rond">
        <h2>5</h2>
      </div>
      <h2>Préparation pré-contrôle technique</h2>
    </div>
    <div class="service-text-5">
      <p>Nous offrons un service de préparation pré-contrôle technique pour aider à garantir que votre voiture passe son contrôle technique sans aucune difficulté.</p>
      <br>
      <p>Nous effectuons un contrôle complet de votre voiture et apportons les modifications nécessaires pour qu'elle soit prête pour le contrôle technique.</p>
    </div>
  </div>



  <div class="service-block">
    <div class="service-rond-titre service-titre-6">
      <div class="service-rond">
        <h2>6</h2>
      </div>
      <h2>Financement avec Financo</h2>
    </div>
    <div class="service-text-6">
      <p>Nous sommes fiers de travailler en partenariat avec Financo pour offrir des solutions de financement pour l'achat de votre véhicule. Nous offrons des taux compétitifs et des conditions de remboursement flexibles pour aider à rendre l'achat de votre voiture plus accessible.</p>
    </div>
  </div>

</div>


<script>

  // tout les titres sauf n1 qui est un temps


  window.addEventListener('scroll', function() {
    var scrollPosition = window.scrollY;
    var scrollServiceTitreDeux = document.querySelector('.service-titre-2');

    if (scrollPosition > 22) {
      scrollServiceTitreDeux.classList.add('show');
    } else {
      scrollServiceTitreDeux.classList.remove('show');
    }
  });

  window.addEventListener('scroll', function() {
    var scrollPosition = window.scrollY;
    var scrollServiceTitreTrois = document.querySelector('.service-titre-3');

    if (scrollPosition > 558) {
      scrollServiceTitreTrois.classList.add('show');
    } else {
      scrollServiceTitreTrois.classList.remove('show');
    }
  });

  window.addEventListener('scroll', function() {
    var scrollPosition = window.scrollY;
    var scrollServiceTitreQuatre = document.querySelector('.service-titre-4');

    if (scrollPosition > 910) {
      scrollServiceTitreQuatre.classList.add('show');
    } else {
      scrollServiceTitreQuatre.classList.remove('show');
    }
  });

  window.addEventListener('scroll', function() {
    var scrollPosition = window.scrollY;
    var scrollServiceTitreCinq = document.querySelector('.service-titre-5');

    if (scrollPosition > 1322) {
      scrollServiceTitreCinq.classList.add('show');
    } else {
      scrollServiceTitreCinq.classList.remove('show');
    }
  });

  window.addEventListener('scroll', function() {
    var scrollPosition = window.scrollY;
    var scrollServiceTitreSix = document.querySelector('.service-titre-6');

    if (scrollPosition > 1700) {
      scrollServiceTitreSix.classList.add('show');
    } else {
      scrollServiceTitreSix.classList.remove('show');
    }
  });

  // tout les texts sauf n1



  window.addEventListener('scroll', function() {
    var scrollPosition = window.scrollY;
    var scrollServiceTextDeux = document.querySelector('.service-text-2');

    if (scrollPosition > 130) {
      scrollServiceTextDeux.classList.add('show');
    } else {
      scrollServiceTextDeux.classList.remove('show');
    }
  });

  window.addEventListener('scroll', function() {
    var scrollPosition = window.scrollY;
    var scrollServiceTextTrois = document.querySelector('.service-text-3');

    if (scrollPosition > 668) {
      scrollServiceTextTrois.classList.add('show');
    } else {
      scrollServiceTextTrois.classList.remove('show');
    }
  });

  window.addEventListener('scroll', function() {
    var scrollPosition = window.scrollY;
    var scrollServiceTextQuatre = document.querySelector('.service-text-4');

    if (scrollPosition > 1020) {
      scrollServiceTextQuatre.classList.add('show');
    } else {
      scrollServiceTextQuatre.classList.remove('show');
    }
  });

  window.addEventListener('scroll', function() {
    var scrollPosition = window.scrollY;
    var scrollServiceTextCinq = document.querySelector('.service-text-5');

    if (scrollPosition > 1432) {
      scrollServiceTextCinq.classList.add('show');
    } else {
      scrollServiceTextCinq.classList.remove('show');
    }
  });

  window.addEventListener('scroll', function() {
    var scrollPosition = window.scrollY;
    var scrollServiceTextSix = document.querySelector('.service-text-6');

    if (scrollPosition > 1810) {
      scrollServiceTextSix.classList.add('show');
    } else {
      scrollServiceTextSix.classList.remove('show');
    }
  });
</script>